# Solving linear equations using the inverse matrix


You go to the shops on Monday and buy 1 apple, 1 banana, and 1 carrot; the whole transaction totals €15. On Tuesday you buy 3 apples, 2 bananas, 1 carrot, all for €28. Then on Wednesday 2 apples, 1 banana, 2 carrots, for €23.

What are the prices of apples, bananas, and carrots?


Use this to solve the following linear system `Ar=s` with numpy

In [1]:
import numpy as np

In [2]:
A = [[1, 1, 1],
     [3, 2, 1],
     [2, 1, 2]]

s = [15,28,23]

The solution of system is 

In [5]:
r = np.linalg.solve(A, s)
print(r)


[3. 7. 5.]


Other example

In [6]:
A = [[3,4],[4,-3]]
s = [10,-5]
r = np.linalg.solve(A,s)
print(r)

[0.4 2.2]


# Inverse matriz

In [7]:
A = [[1, 1, 3],
     [1, 2, 4],
     [1, 1, 2]]
Ainv = np.linalg.inv(A)
print(Ainv)

[[ 0. -1.  2.]
 [-2.  1.  1.]
 [ 1. -0. -1.]]
